version: '3.8'

services:
  fleetform-cli:
    build:
      context: .
      dockerfile: Dockerfile.cli
    volumes:
      - .:/workspace
      - ~/.aws:/root/.aws:ro
    working_dir: /workspace
    environment:
      - RUST_LOG=info
    command: ["tail", "-f", "/dev/null"]

  fleetform-web:
    build:
      context: ./fiber
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - GIN_MODE=release
    depends_on:
      - fleetform-cli
    volumes:
      - ./fiber:/app
      - .:/workspace:ro

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  redis_data: