name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: fleetform
            asset_name: fleetform-linux-amd64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: fleetform.exe
            asset_name: fleetform-windows-amd64.exe
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: fleetform
            asset_name: fleetform-macos-amd64
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.target }}
    - run: cargo build --release --target ${{ matrix.target }}
    - uses: softprops/action-gh-release@v1
      with:
        files: target/${{ matrix.target }}/release/${{ matrix.artifact_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}